app_home:
    path: /
    controller: App\Controller\HomeController::index

app_race_index:
    path: /races
    controller: App\Controller\RaceController::index
app_post_show:
    path: /races/{id}
    controller: App\Controller\RaceController::show