# Home
app_home:
    path: /
    controller: App\Controller\HomeController::index

# Authentication
app_register:
    path: /signup
    controller: App\Controller\RegistrationController::register
app_login:
    path: /login
    controller: App\Controller\AuthController::login
app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout

# User
app_user_show:
    path: /user/{id}
    controller: App\Controller\UserController::show

# Races
app_race_index:
    path: /races
    controller: App\Controller\RaceController::index
app_race_new:
    path: /races/new
    controller: App\Controller\RaceController::create
app_race_show:
    path: /races/{slug}
    controller: App\Controller\RaceController::show
app_race_edit:
    path: /races/edit/{slug}
    controller: App\Controller\RaceController::edit
app_race_delete:
    path: /races/delete/{slug}
    controller: App\Controller\RaceController::delete

# Provinces
app_province_index:
    path: /provinces
    controller: App\Controller\ProvinceController::index
app_province_new:
    path: /provinces/new
    controller: App\Controller\ProvinceController::create
app_province_show:
    path: /provinces/{slug}
    controller: App\Controller\ProvinceController::show
app_province_edit:
    path: /provinces/edit/{slug}
    controller: App\Controller\ProvinceController::edit
app_province_delete:
    path: /provinces/delete/{slug}
    controller: App\Controller\ProvinceController::delete

# Skills
app_skill_index:
    path: /skills
    controller: App\Controller\SkillController::index
app_skill_new:
    path: /skills/new
    controller: App\Controller\SkillController::create
app_skill_show:
    path: /skills/{slug}
    controller: App\Controller\SkillController::show
app_skill_edit:
    path: /skills/edit/{slug}
    controller: App\Controller\SkillController::edit
app_skill_delete:
    path: /skills/delete/{slug}
    controller: App\Controller\SkillController::delete

# Cities
app_city_index:
    path: /cities
    controller: App\Controller\CityController::index
app_city_new:
    path: /cities/new
    controller: App\Controller\CityController::create
app_city_show:
    path: /cities/{slug}
    controller: App\Controller\CityController::show
app_city_edit:
    path: /cities/edit/{slug}
    controller: App\Controller\CityController::edit
app_city_delete:
    path: /cities/delete/{slug}
    controller: App\Controller\CityController::delete

# Followers
app_follower_index:
    path: /followers
    controller: App\Controller\FollowerController::index
app_follower_new:
    path: /followers/new
    controller: App\Controller\FollowerController::create
app_follower_show:
    path: /followers/{slug}
    controller: App\Controller\FollowerController::show
app_follower_edit:
    path: /followers/edit/{slug}
    controller: App\Controller\FollowerController::edit
app_follower_delete:
    path: /followers/delete/{slug}
    controller: App\Controller\FollowerController::delete