# Home
app_home:
    path: /
    controller: App\Controller\HomeController::index

# Races
app_race_index:
    path: /races
    controller: App\Controller\RaceController::index
app_race_new:
    path: /races/new
    controller: App\Controller\RaceController::create
app_race_show:
    path: /races/{slug}
    controller: App\Controller\RaceController::show
app_race_edit:
    path: /races/edit/{slug}
    controller: App\Controller\RaceController::edit
app_race_delete:
    path: /races/delete/{slug}
    controller: App\Controller\RaceController::delete

# Provinces
app_province_index:
    path: /provinces
    controller: App\Controller\ProvinceController::index
app_province_new:
    path: /provinces/new
    controller: App\Controller\ProvinceController::create
app_province_show:
    path: /provinces/{slug}
    controller: App\Controller\ProvinceController::show
app_province_edit:
    path: /provinces/edit/{slug}
    controller: App\Controller\ProvinceController::edit
app_province_delete:
    path: /provinces/delete/{slug}
    controller: App\Controller\ProvinceController::delete

# Skills
app_skill_index:
    path: /skills
    controller: App\Controller\SkillController::index
app_skill_show:
    path: /skills/{id}
    controller: App\Controller\SkillController::show